ARG image=ubuntu:bionic

FROM ${image} as source-internet

FROM source-internet as builder

RUN apt-get update --quiet
RUN apt-get install --quiet --assume-yes \
      git  \
      build-essential \
      qt5-default \
      qtbase5-dev \
      qtscript5-dev \
      qttools5-dev-tools

COPY . /repo
WORKDIR /repo
RUN chmod +x build_linux_portable.sh
RUN ./build_linux_portable.sh
